services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    container_name: rag_robot
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=rag_robot
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["uvicorn", "src.bot_app.app:app", "--host", "0.0.0.0", "--port", "8000"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mysql_data:
